autoMachine/urls.py
from django.urls import path, include
from .views import *
app_name='autoMachine'

urlpatterns = [
    path('', mainview ),
    path('scrap/', scrap, name='scrap' ),
    path('submitScrap/', submitScrap, name='submitScrap'),
    path('chat/', include('chat.urls')),

]

chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<str:user_id>/', views.index, name='index'),
]

pangcode/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autoMachine.urls')),
]

autoMachine/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

# Create your models here.

autoMachine/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from .auto_scraper import *

from django.http import JsonResponse


# Create your views here.

def mainview(request) :
    return render(request, "autoMachine/index.html")


def scrap(request) :
    run_main()
    return JsonResponse({'msg': '작업이 종료되었습니다'})


def submitScrap(request) :
    getDate = request.POST.get('postDate','')
    getActResult = run_main( getDate )

    if getActResult == 'dateError' :
        return JsonResponse({'msg': '날짜 입력오류'})
    else :
        return JsonResponse({'msg': '작업이 종료되었습니다'})
    
    

    # return HttpResponseRedirect( reverse('board:gotolist'))
    # return HttpResponse(getDate)

chat/views.py
from django.shortcuts import render

def index(request, user_id):
    '''
    프로그램 시작 / 로깅 html을 응답으로 주는 뷰
    '''
    return render(request, 'chat/logs.html', {
        'user_id': user_id
    })

autoMachine/templates/autoMachine/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    
    <form method="POST" action="{% url 'autoMachine:submitScrap' %}">{% csrf_token %}

        <input type="date" name="postDate" >
        <input type="submit" id="btnSubmit" value="주문취합실행">
        <br>
        <br>
        <br>

        <button onclick="run()">실행</button>

    </form>

    

    <div id="dataResult"></div>

</body>

<script>
    function run(){
          const xhttp = new XMLHttpRequest();
          xhttp.onload = function() {
          let result = JSON.parse(this.responseText);
            document.getElementById("dataResult").innerHTML = result.msg;
            }
          xhttp.open("GET", "{% url 'autoMachine:scrap' %}", true);
          xhttp.send();
    }
</script>
</html>

chat/templates/chat/logs.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Logging</title>
</head>

<body>
    <h1>{{user_id}}: Scraping...</h1>
    <textarea id="log-area" cols="100" rows="20"></textarea><br/>
    <input id="start-process-btn" type="button" value="Send"/>
</body>

<script>
    var userId = '{{ user_id }}';

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chat/' + userId + '/');

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        document.querySelector('#log-area').value += (message + '\n');
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#start-process-btn').onclick = function(e) {
        chatSocket.send('');
        console.log('send finished');
    };
</script>

</html>